### ISSUE TITLE
mounting of table folder failed

### ISSUE THREAD

**Issue by andersryanc** [liblouis/liblouis-js#46]
I just installed a fresh copy of `liblouis` (^0.3.0) and `liblouis-build` (^3.2.0-rc) into a blank node project and tried to just console.log the liblouis object, like:

```
const liblouis = require("liblouis");
console.log(liblouis);
```

and upon running `node index.js` I get the following error:

```
/Users/ryan/code/js/liblouis-test/node_modules/liblouis-build/build-no-tables-utf16.js:115
      throw ex;
      ^

Error: mounting of table folder failed
    at Object.liblouis.enableOnDemandTableLoading (/Users/ryan/code/js/liblouis-test/node_modules/liblouis/easy-api.js:219:15)
    at Object.setLiblouisBuild (/Users/ryan/code/js/liblouis-test/node_modules/liblouis/easy-api.js:62:16)
    at Object.<anonymous> (/Users/ryan/code/js/liblouis-test/node_modules/liblouis/liblouis.js:3:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

I seem to have tracked down this error to `capi.NODEFS === undefined` in `liblouis/easy-api.js`. Specifically, in `liblouis.enableOnDemandTableLoading()` in the `try` block around:
```
capi.FS.mount(capi.NODEFS, { root: tablefolder }, "/tables");
```

I was able to get things working again by changing that line to:

```
capi.FS.mount(capi.FS.filesystems.NODEFS, { root: tablefolder }, "/tables");
```

Is this just a bug in the code? or am I doing something wrong?

**Comment by andersryanc** [comment]
I guess I should have looked over the latest source code... I see that this issue seems to be fixed there: https://github.com/liblouis/liblouis-js/blob/76595fcac24d38a2d24f0dd3a04c4c6671cdbf76/easy-api.js#L264

Any plans to release an update to NPM sometime soon?

**Comment by reiner-dolp** [comment]
Yeah, I am sorry for wasting your time tracking down this bug. Please use

```
npm install liblouis/js-build
npm install liblouis/liblouis-js
```
until the NPM packages are updated.

---
See https://github.com/liblouis/liblouis/issues/569

**Comment by andersryanc** [comment]
No worries. Thanks for letting me know about this way of installing it.
